name: Termux Engine

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    name: Termux Engine - ${{ matrix.name }}
    uses: ./.github/workflows/build.yml

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows x64
            os: windows-2022
            buildArgs: windows
            artifactName: TermuxEngine-Windows-x64
            artifactPath: export/release/windows/bin/*

          - name: Linux
            os: ubuntu-22.04
            buildArgs: linux
            artifactName: TermuxEngine-Linux
            artifactPath: export/release/linux/bin/*

          # 🔥 Android agora no Linux (sem macOS)
          - name: Android
            os: ubuntu-22.04
            buildArgs: "android -ONLY_ARM64"
            artifactName: TermuxEngine-Android
            artifactPath: export/release/android/bin/app/build/outputs/apk/release/*.apk

    with:
      name: Termux Engine - ${{ matrix.name }}
      os: ${{ matrix.os }}
      buildArgs: ${{ matrix.buildArgs }}
      artifactName: ${{ matrix.artifactName }}
      artifactPath: ${{ matrix.artifactPath }}